### ISSUE TITLE
FEATURE REQUEST: Darkmode

### ISSUE THREAD

**Issue by julius-gmeinder** [ljcoder2015/obsidian-sheet-plus#41]
Not actually a problem but the sheet is just very bright and hard on the eyes. I think a darkmode setting would improve comfort alot, especially most obsidian users use dark mode by default

![image](https://github.com/user-attachments/assets/32bb2da9-bfbd-475e-ba73-ddc4ff752190)

**Comment by YongcaiHuang** [comment]
it's a great plugin!! I agree with adding the dark mode support. it would be really aesthetic if sheet theme is consistent with obsidian theme, esp. embeding sheet into md note.

**Comment by ifulou** [comment]
+1

**Comment by piotrnajda3000** [comment]
+1

**Comment by piotrnajda3000** [comment]
This CSS snippet seems to work fine:

```css
#sheet-box, .univer-menu, .univer-toolbar-more-container, .univer-defined-name-overlay {
 filter: invert(0.88) brightness(1.3) hue-rotate(180deg);
}
```

![Image](https://github.com/user-attachments/assets/7cd8b211-126a-4a98-91a6-ba2d907d1692)

**Comment by Accelsnow** [comment]
> This CSS snippet seems to work fine (you might turn down the brightness or increase `invert` to your liking):
> 
> #sheet-box, .univer-menu, .univer-toolbar-more-container, .univer-defined-name-overlay {
>  filter: invert(0.88) brightness(1.3) hue-rotate(180deg);
> }
> ![Image](https://github.com/user-attachments/assets/7cd8b211-126a-4a98-91a6-ba2d907d1692)

Can confirm this works like a charm!

**Comment by cj81499** [comment]
I suspect the main blocker here is upstream support for dark mode. See https://github.com/dream-num/univer/issues/4511

**Comment by cj81499** [comment]
The custom CSS workaround still works for me.

**Comment by JacobHamelMottiez** [comment]
> The custom CSS workaround still works for me.

And you just save and load the CSS snippet in the CSS snippets in the Appearance section ? I just tried in an empty vault to exclude conflicting and it still doesn't work. Thanks for your help!

**Comment by cj81499** [comment]
In my snippets folder, I have one file `dark-univer-sheet.css`.

I actually use a slightly modified version of the css above:

```css
.univer-theme {
    filter: invert(0.9) brightness(1) hue-rotate(180deg);
}
```

Make sure it's enabled in the Obsidian UI: 

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/effdbd57-17ba-48c1-aab0-3f434a3d84aa" />
